"""empty message

Revision ID: 01219e3b059f
Revises: 7f35b3bcbbd8
Create Date: 2017-10-06 10:54:41.724755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01219e3b059f'
down_revision = '7f35b3bcbbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'username')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
