"""empty message

Revision ID: 701f5827185b
Revises: 
Create Date: 2017-09-27 09:01:34.326772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '701f5827185b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('budget', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('budget', 'date')
    op.add_column('budget_item', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('budget_item', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('budget_item', sa.Column('year', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'budget_item', 'account', ['account_id'], ['id'])
    op.drop_column('budget_item', 'date')
    op.add_column('expense', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('expense', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('expense', 'date')
    op.add_column('revenue', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('revenue', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('revenue', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('revenue', 'year')
    op.drop_column('revenue', 'month')
    op.add_column('expense', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('expense', 'year')
    op.drop_column('expense', 'month')
    op.add_column('budget_item', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'budget_item', type_='foreignkey')
    op.drop_column('budget_item', 'year')
    op.drop_column('budget_item', 'month')
    op.drop_column('budget_item', 'account_id')
    op.add_column('budget', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('budget', 'year')
    op.drop_column('budget', 'month')
    # ### end Alembic commands ###
